{
 "title": "Adventure Land",
 "description": "Some useful metrics taken from Adventure Land",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": { "query": "label_values(server)" } },
   { "name": "character", "label": "Character", "query": { "query": "label_values(character)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Characters running code",
   "type": "stat",
   "description": "How many characters are currently sending metrics?",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (al_character_info{name=~\"$character\"})"
    }
   ]
  },
  {
   "title": "Max level",
   "type": "stat",
   "description": "Highest level character",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, last_over_time(al_level_total[10y]))"
    }
   ]
  },
  {
   "title": "Total gold",
   "type": "stat",
   "description": "How much gold do I have across all characters",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(al_gold_total[10y]))"
    }
   ]
  },
  {
   "title": "Looted gold per hour",
   "type": "stat",
   "description": "Gold per hour for every character",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(al_looted_gold_total{server =~ \"$server\", character =~ \"$character\"}[10m])) * 1h default 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gold variation over time range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(al_gold_total{character =~ \"$character\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time range",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Most killed monsters",
   "type": "table",
   "description": "Which one do I hate most?",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(20, sum by (enemy) (increase(al_kills_total{server =~ \"$server\", character =~ \"$character\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Most looted items",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, sum by (item) (increase(al_looted_items_total{server =~ \"$server\", character =~ \"$character\"}[$__range])) > 0)"
    }
   ]
  },
  {
   "title": "Looted gold per hour",
   "type": "timeseries",
   "description": "Total looted gold",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(al_looted_gold_total{server =~ \"$server\", character =~ \"$character\"}[10m])) * 1h default 0",
     "legendFormat": "Gold"
    }
   ]
  },
  {
   "title": "Owned gold",
   "type": "timeseries",
   "description": "Total gold owned",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (last_over_time(al_gold_total{character =~ \"$character\"}[10y])) default 0",
     "legendFormat": "Total owned gold"
    }
   ]
  },
  {
   "title": "Damage per second",
   "type": "graph",
   "description": "Damage per second for every character",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(character) (rate(al_damage_dealt_total{damage_type != \"\", character =~ \"$character\", server =~ \"$server\"}[1m]))",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Exp per hour",
   "type": "graph",
   "description": "Exp per hour for every character",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(character) (rate(al_exp_total{character =~ \"$character\"}[5m])) * 1h",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "timeseries",
   "description": "How many times did they die?",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(al_deaths_total{server =~ \"$server\", character =~ \"$character\"}[10y])",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Online timeline",
   "type": "state-timeline",
   "description": "Show online history of characters",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "al_character_info{character=~\"$character\"} default 0",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "All time all servers all characters metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "[ALL TIME] Most killed monsters",
   "type": "table",
   "description": "Which one do I hate most?",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(20, sum by (enemy) (increase(al_kills_total[10y])))"
    }
   ]
  },
  {
   "title": "[ALL TIME] Most looted items",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, sum by (item) (increase(al_looted_items_total[10y])) > 0)"
    }
   ]
  },
  {
   "title": "[ALL TIME] Most bought items",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, sum by (item) (increase(al_bought_items_total[10y])) > 0)"
    }
   ]
  },
  {
   "title": "[ALL TIME] Most sold items",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, sum by (item) (increase(al_sold_items_total[10y])) > 0)"
    }
   ]
  },
  {
   "title": "[ALL TIME] Most used skills",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, sum by (skill) (increase(al_used_skills_total[10y])) > 0)"
    }
   ]
  },
  {
   "title": "[ALL TIME] Most opened chests",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, sum by (skin) (increase(al_opened_chests_total[10y])) > 0)"
    }
   ]
  }
 ]
}